import { corsHeaders } from '../_shared/cors.ts'
import { supabaseAdmin } from '../_shared/supabaseAdmin.ts'
import { supabaseAuthed } from '../_shared/supabaseAuthed.ts'
import { twilioClient, twilioFromNumber } from '../_shared/twilio.ts'

type Body = {
  job_id: string
  reason: 'customer_cancelled' | 'technician_unavailable' | 'rescheduled'
  reason_details?: string
}

function json(status: number, body: unknown) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  })
}

async function sendExpoPush(tokens: string[], payload: { title: string; body: string; data?: Record<string, unknown> }) {
  if (!tokens.length) return
  await fetch('https://exp.host/--/api/v2/push/send', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(
      tokens.map((to) => ({
        to,
        title: payload.title,
        body: payload.body,
        data: payload.data ?? {},
      })),
    ),
  })
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders })
  if (req.method !== 'POST') return json(405, { error: 'Method not allowed' })

  const sb = supabaseAuthed(req)
  const { data: userRes, error: userErr } = await sb.auth.getUser()
  const user = userRes?.user
  if (userErr || !user) return json(401, { error: 'Unauthorized' })

  let body: Body
  try {
    body = (await req.json()) as Body
  } catch {
    return json(400, { error: 'Invalid JSON' })
  }
  if (!body.job_id) return json(400, { error: 'Missing job_id' })
  if (!body.reason) return json(400, { error: 'Missing reason' })

  const admin = supabaseAdmin()

  const { data: job, error: jobErr } = await admin
    .from('jobs')
    .select(
      'id, owner_id, technician_id, status, title, job_type, scheduled_at, customer_id, customers(name, phone, address, lat, lng), technicians(id, name, user_id)',
    )
    .eq('id', body.job_id)
    .maybeSingle()
  if (jobErr || !job) return json(404, { error: jobErr?.message ?? 'Job not found' })

  if (job.owner_id !== user.id) return json(403, { error: 'Only the owner can cancel jobs' })
  if (job.status === 'cancelled') return json(409, { error: 'Job already cancelled' })
  if (job.status === 'completed') return json(409, { error: 'Cannot cancel a completed job' })

  const nowIso = new Date().toISOString()

  // Update job to cancelled
  const { error: upErr } = await admin
    .from('jobs')
    .update({
      status: 'cancelled',
      cancelled_at: nowIso,
      cancel_reason: body.reason,
      cancel_reason_details: body.reason_details?.trim() || null,
      cancelled_by: user.id,
    })
    .eq('id', job.id)
  if (upErr) return json(500, { error: upErr.message })

  // Free technician if they have no other in-progress jobs
  if (job.technician_id) {
    const { count } = await admin
      .from('jobs')
      .select('id', { count: 'exact', head: true })
      .eq('technician_id', job.technician_id)
      .eq('owner_id', job.owner_id)
      .eq('status', 'in_progress')
    if ((count ?? 0) === 0) {
      await admin.from('technicians').update({ status: 'available' }).eq('id', job.technician_id).eq('owner_id', job.owner_id)
    }
  }

  // Customer SMS
  const custPhone = job.customers?.phone?.trim()
  if (custPhone) {
    try {
      const twilio = twilioClient()
      await twilio.messages.create({
        to: custPhone,
        from: twilioFromNumber(),
        body: "Your appointment has been cancelled. We'll be in touch to reschedule.",
      })
    } catch {
      // ignore SMS failures (still cancelled)
    }
  }

  // Technician push: "Job at [address] has been cancelled"
  const techUser = job.technicians?.user_id ?? null
  const addr = job.customers?.address?.trim() || 'the customer location'
  if (techUser) {
    const { data: toks } = await admin.from('expo_push_tokens').select('token').eq('user_id', techUser).order('updated_at', { ascending: false }).limit(3)
    const tokens = (toks ?? []).map((t) => (t as { token: string }).token).filter(Boolean)
    await sendExpoPush(tokens, { title: 'Job cancelled', body: `Job at ${addr} has been cancelled`, data: { job_id: job.id } })
  }

  // Owner notification is generated by DB trigger on jobs.status='cancelled'

  return json(200, { ok: true })
})

